# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_platform/skylab_test_runner/cft_steps_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7test_platform/skylab_test_runner/cft_steps_config.proto\x12 test_platform.skylab_test_runner\"i\n\x0e\x43\x66tStepsConfig\x12H\n\x0ehw_test_config\x18\x01 \x01(\x0b\x32..test_platform.skylab_test_runner.HwTestConfigH\x00\x42\r\n\x0b\x63onfig_type\"\xb2\x01\n\x0cHwTestConfig\x12\x16\n\x0eskip_provision\x18\x01 \x01(\x08\x12\x1b\n\x13skip_test_execution\x18\x02 \x01(\x08\x12\x1f\n\x17skip_all_result_publish\x18\x03 \x01(\x08\x12\x18\n\x10skip_gcs_publish\x18\x04 \x01(\x08\x12\x18\n\x10skip_rdb_publish\x18\x05 \x01(\x08\x12\x18\n\x10skip_tko_publish\x18\x06 \x01(\x08\x42LZJgo.chromium.org/chromiumos/infra/proto/go/test_platform/skylab_test_runnerb\x06proto3')



_CFTSTEPSCONFIG = DESCRIPTOR.message_types_by_name['CftStepsConfig']
_HWTESTCONFIG = DESCRIPTOR.message_types_by_name['HwTestConfig']
CftStepsConfig = _reflection.GeneratedProtocolMessageType('CftStepsConfig', (_message.Message,), {
  'DESCRIPTOR' : _CFTSTEPSCONFIG,
  '__module__' : 'test_platform.skylab_test_runner.cft_steps_config_pb2'
  # @@protoc_insertion_point(class_scope:test_platform.skylab_test_runner.CftStepsConfig)
  })
_sym_db.RegisterMessage(CftStepsConfig)

HwTestConfig = _reflection.GeneratedProtocolMessageType('HwTestConfig', (_message.Message,), {
  'DESCRIPTOR' : _HWTESTCONFIG,
  '__module__' : 'test_platform.skylab_test_runner.cft_steps_config_pb2'
  # @@protoc_insertion_point(class_scope:test_platform.skylab_test_runner.HwTestConfig)
  })
_sym_db.RegisterMessage(HwTestConfig)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZJgo.chromium.org/chromiumos/infra/proto/go/test_platform/skylab_test_runner'
  _CFTSTEPSCONFIG._serialized_start=93
  _CFTSTEPSCONFIG._serialized_end=198
  _HWTESTCONFIG._serialized_start=201
  _HWTESTCONFIG._serialized_end=379
# @@protoc_insertion_point(module_scope)
