# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromite/telemetry/clientanalytics.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(chromite/telemetry/clientanalytics.proto\x12\x12\x63hromite.telemetry\"<\n\x08LogEvent\x12\x15\n\revent_time_ms\x18\x01 \x01(\x03\x12\x19\n\x10source_extension\x18\xa6\t \x01(\x0c\"!\n\nClientInfo\x12\x13\n\x0b\x63lient_type\x18\x01 \x01(\x05\"\x9f\x01\n\nLogRequest\x12\x33\n\x0b\x63lient_info\x18\x01 \x01(\x0b\x32\x1e.chromite.telemetry.ClientInfo\x12\x12\n\nlog_source\x18\x02 \x01(\x05\x12\x17\n\x0frequest_time_ms\x18\x04 \x01(\x03\x12/\n\tlog_event\x18\x03 \x03(\x0b\x32\x1c.chromite.telemetry.LogEvent\"/\n\x0bLogResponse\x12 \n\x18next_request_wait_millis\x18\x01 \x01(\x03\x42>Z<go.chromium.org/chromiumos/infra/proto/go/chromite/telemetry')



_LOGEVENT = DESCRIPTOR.message_types_by_name['LogEvent']
_CLIENTINFO = DESCRIPTOR.message_types_by_name['ClientInfo']
_LOGREQUEST = DESCRIPTOR.message_types_by_name['LogRequest']
_LOGRESPONSE = DESCRIPTOR.message_types_by_name['LogResponse']
LogEvent = _reflection.GeneratedProtocolMessageType('LogEvent', (_message.Message,), {
  'DESCRIPTOR' : _LOGEVENT,
  '__module__' : 'chromite.telemetry.clientanalytics_pb2'
  # @@protoc_insertion_point(class_scope:chromite.telemetry.LogEvent)
  })
_sym_db.RegisterMessage(LogEvent)

ClientInfo = _reflection.GeneratedProtocolMessageType('ClientInfo', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTINFO,
  '__module__' : 'chromite.telemetry.clientanalytics_pb2'
  # @@protoc_insertion_point(class_scope:chromite.telemetry.ClientInfo)
  })
_sym_db.RegisterMessage(ClientInfo)

LogRequest = _reflection.GeneratedProtocolMessageType('LogRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOGREQUEST,
  '__module__' : 'chromite.telemetry.clientanalytics_pb2'
  # @@protoc_insertion_point(class_scope:chromite.telemetry.LogRequest)
  })
_sym_db.RegisterMessage(LogRequest)

LogResponse = _reflection.GeneratedProtocolMessageType('LogResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOGRESPONSE,
  '__module__' : 'chromite.telemetry.clientanalytics_pb2'
  # @@protoc_insertion_point(class_scope:chromite.telemetry.LogResponse)
  })
_sym_db.RegisterMessage(LogResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z<go.chromium.org/chromiumos/infra/proto/go/chromite/telemetry'
  _LOGEVENT._serialized_start=64
  _LOGEVENT._serialized_end=124
  _CLIENTINFO._serialized_start=126
  _CLIENTINFO._serialized_end=159
  _LOGREQUEST._serialized_start=162
  _LOGREQUEST._serialized_end=321
  _LOGRESPONSE._serialized_start=323
  _LOGRESPONSE._serialized_end=370
# @@protoc_insertion_point(module_scope)
