# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/test/api/android_provision.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromite.api.gen_sdk.chromiumos.test.api import android_provision_metadata_pb2 as chromiumos_dot_test_dot_api_dot_android__provision__metadata__pb2
from chromite.api.gen_sdk.chromiumos.test.lab.api import dut_pb2 as chromiumos_dot_test_dot_lab_dot_api_dot_dut__pb2
from chromite.api.gen_sdk.chromiumos.test.lab.api import ip_endpoint_pb2 as chromiumos_dot_test_dot_lab_dot_api_dot_ip__endpoint__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+chromiumos/test/api/android_provision.proto\x12\x13\x63hromiumos.test.api\x1a\x34\x63hromiumos/test/api/android_provision_metadata.proto\x1a!chromiumos/test/lab/api/dut.proto\x1a)chromiumos/test/lab/api/ip_endpoint.proto\"\xdf\x01\n\x15\x41ndroidProvisionState\x12\x39\n\x02id\x18\x01 \x01(\x0b\x32-.chromiumos.test.api.AndroidProvisionState.Id\x12\x37\n\rcipd_packages\x18\x02 \x03(\x0b\x32 .chromiumos.test.api.CIPDPackage\x12=\n\x10\x61ndroid_os_image\x18\x03 \x01(\x0b\x32#.chromiumos.test.api.AndroidOsImage\x1a\x13\n\x02Id\x12\r\n\x05value\x18\x01 \x01(\t\"\xc2\x01\n\x17\x41ndroidProvisionRequest\x12)\n\x03\x64ut\x18\x01 \x01(\x0b\x32\x1c.chromiumos.test.lab.api.Dut\x12\x43\n\x0fprovision_state\x18\x02 \x01(\x0b\x32*.chromiumos.test.api.AndroidProvisionState\x12\x37\n\ndut_server\x18\x03 \x01(\x0b\x32#.chromiumos.test.lab.api.IpEndpointB/Z-go.chromium.org/chromiumos/config/go/test/apib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chromiumos.test.api.android_provision_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z-go.chromium.org/chromiumos/config/go/test/api'
  _ANDROIDPROVISIONSTATE._serialized_start=201
  _ANDROIDPROVISIONSTATE._serialized_end=424
  _ANDROIDPROVISIONSTATE_ID._serialized_start=405
  _ANDROIDPROVISIONSTATE_ID._serialized_end=424
  _ANDROIDPROVISIONREQUEST._serialized_start=427
  _ANDROIDPROVISIONREQUEST._serialized_end=621
# @@protoc_insertion_point(module_scope)
