# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/test/api/android_provision_state.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromite.api.gen_sdk.chromiumos.test.api import android_provision_metadata_pb2 as chromiumos_dot_test_dot_api_dot_android__provision__metadata__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='chromiumos/test/api/android_provision_state.proto',
  package='chromiumos.test.api',
  syntax='proto3',
  serialized_options=b'Z-go.chromium.org/chromiumos/config/go/test/api',
  serialized_pb=b'\n1chromiumos/test/api/android_provision_state.proto\x12\x13\x63hromiumos.test.api\x1a\x34\x63hromiumos/test/api/android_provision_metadata.proto\"\xa0\x01\n\x15\x41ndroidProvisionState\x12\x39\n\x02id\x18\x01 \x01(\x0b\x32-.chromiumos.test.api.AndroidProvisionState.Id\x12\x37\n\rcipd_packages\x18\x02 \x03(\x0b\x32 .chromiumos.test.api.CIPDPackage\x1a\x13\n\x02Id\x12\r\n\x05value\x18\x01 \x01(\tB/Z-go.chromium.org/chromiumos/config/go/test/apib\x06proto3'
  ,
  dependencies=[chromiumos_dot_test_dot_api_dot_android__provision__metadata__pb2.DESCRIPTOR,])




_ANDROIDPROVISIONSTATE_ID = _descriptor.Descriptor(
  name='Id',
  full_name='chromiumos.test.api.AndroidProvisionState.Id',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='chromiumos.test.api.AndroidProvisionState.Id.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=289,
)

_ANDROIDPROVISIONSTATE = _descriptor.Descriptor(
  name='AndroidProvisionState',
  full_name='chromiumos.test.api.AndroidProvisionState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='chromiumos.test.api.AndroidProvisionState.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cipd_packages', full_name='chromiumos.test.api.AndroidProvisionState.cipd_packages', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ANDROIDPROVISIONSTATE_ID, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=289,
)

_ANDROIDPROVISIONSTATE_ID.containing_type = _ANDROIDPROVISIONSTATE
_ANDROIDPROVISIONSTATE.fields_by_name['id'].message_type = _ANDROIDPROVISIONSTATE_ID
_ANDROIDPROVISIONSTATE.fields_by_name['cipd_packages'].message_type = chromiumos_dot_test_dot_api_dot_android__provision__metadata__pb2._CIPDPACKAGE
DESCRIPTOR.message_types_by_name['AndroidProvisionState'] = _ANDROIDPROVISIONSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AndroidProvisionState = _reflection.GeneratedProtocolMessageType('AndroidProvisionState', (_message.Message,), {

  'Id' : _reflection.GeneratedProtocolMessageType('Id', (_message.Message,), {
    'DESCRIPTOR' : _ANDROIDPROVISIONSTATE_ID,
    '__module__' : 'chromiumos.test.api.android_provision_state_pb2'
    # @@protoc_insertion_point(class_scope:chromiumos.test.api.AndroidProvisionState.Id)
    })
  ,
  'DESCRIPTOR' : _ANDROIDPROVISIONSTATE,
  '__module__' : 'chromiumos.test.api.android_provision_state_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.api.AndroidProvisionState)
  })
_sym_db.RegisterMessage(AndroidProvisionState)
_sym_db.RegisterMessage(AndroidProvisionState.Id)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
