# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/test/api/android_provision_cli.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromite.api.gen_sdk.chromiumos.test.api import android_provision_metadata_pb2 as chromiumos_dot_test_dot_api_dot_android__provision__metadata__pb2
from chromite.api.gen_sdk.chromiumos.test.api import provision_service_pb2 as chromiumos_dot_test_dot_api_dot_provision__service__pb2
from chromite.api.gen_sdk.chromiumos.test.lab.api import dut_pb2 as chromiumos_dot_test_dot_lab_dot_api_dot_dut__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/chromiumos/test/api/android_provision_cli.proto\x12\x13\x63hromiumos.test.api\x1a\x34\x63hromiumos/test/api/android_provision_metadata.proto\x1a+chromiumos/test/api/provision_service.proto\x1a!chromiumos/test/lab/api/dut.proto\"\x8d\x02\n\x1b\x41ndroidProvisionCLIResponse\x12+\n\x02id\x18\x01 \x01(\x0b\x32\x1f.chromiumos.test.lab.api.Dut.Id\x12\x36\n\x07success\x18\x02 \x01(\x0b\x32#.chromiumos.test.api.InstallSuccessH\x00\x12\x36\n\x07\x66\x61ilure\x18\x03 \x01(\x0b\x32#.chromiumos.test.api.InstallFailureH\x00\x12\x46\n\x10\x61ndroid_packages\x18\x04 \x03(\x0b\x32,.chromiumos.test.api.InstalledAndroidPackageB\t\n\x07outcomeB/Z-go.chromium.org/chromiumos/config/go/test/apib\x06proto3')



_ANDROIDPROVISIONCLIRESPONSE = DESCRIPTOR.message_types_by_name['AndroidProvisionCLIResponse']
AndroidProvisionCLIResponse = _reflection.GeneratedProtocolMessageType('AndroidProvisionCLIResponse', (_message.Message,), {
  'DESCRIPTOR' : _ANDROIDPROVISIONCLIRESPONSE,
  '__module__' : 'chromiumos.test.api.android_provision_cli_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.api.AndroidProvisionCLIResponse)
  })
_sym_db.RegisterMessage(AndroidProvisionCLIResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z-go.chromium.org/chromiumos/config/go/test/api'
  _ANDROIDPROVISIONCLIRESPONSE._serialized_start=207
  _ANDROIDPROVISIONCLIRESPONSE._serialized_end=476
# @@protoc_insertion_point(module_scope)
