# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/test/api/callbox_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)chromiumos/test/api/callbox_service.proto\x12\x13\x63hromiumos.test.api\"\x14\n\x12\x43heckHealthRequest\"\x15\n\x13\x43heckHealthResponse2t\n\x0e\x43\x61llboxService\x12\x62\n\x0b\x43heckHealth\x12\'.chromiumos.test.api.CheckHealthRequest\x1a(.chromiumos.test.api.CheckHealthResponse0\x01\x42/Z-go.chromium.org/chromiumos/config/go/test/apib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chromiumos.test.api.callbox_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z-go.chromium.org/chromiumos/config/go/test/api'
  _CHECKHEALTHREQUEST._serialized_start=66
  _CHECKHEALTHREQUEST._serialized_end=86
  _CHECKHEALTHRESPONSE._serialized_start=88
  _CHECKHEALTHRESPONSE._serialized_end=109
  _CALLBOXSERVICE._serialized_start=111
  _CALLBOXSERVICE._serialized_end=227
# @@protoc_insertion_point(module_scope)
