# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/test/api/cros_test_runner_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2chromiumos/test/api/cros_test_runner_service.proto\x12\x13\x63hromiumos.test.api\"\xef\x01\n\x12RunCrosTestRequest\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\r\n\x05\x62oard\x18\x02 \x01(\t\x12\r\n\x05tests\x18\x03 \x03(\t\x12\x18\n\x10results_dir_name\x18\x04 \x01(\t\x12J\n\rautotest_args\x18\x05 \x03(\x0b\x32\x33.chromiumos.test.api.RunCrosTestRequest.AutotestArg\x12\x1b\n\x13\x63ros_test_image_tag\x18\x06 \x01(\t\x1a*\n\x0b\x41utotestArg\x12\x0c\n\x04\x66lag\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"J\n\x13RunCrosTestResponse\x12\x0e\n\x06stdout\x18\x01 \x01(\t\x12\x0e\n\x06stderr\x18\x02 \x01(\t\x12\x13\n\x0breturn_code\x18\x03 \x01(\x05\x32s\n\x15\x43rosTestRunnerService\x12Z\n\x03Run\x12\'.chromiumos.test.api.RunCrosTestRequest\x1a(.chromiumos.test.api.RunCrosTestResponse\"\x00\x42/Z-go.chromium.org/chromiumos/config/go/test/apib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chromiumos.test.api.cros_test_runner_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z-go.chromium.org/chromiumos/config/go/test/api'
  _RUNCROSTESTREQUEST._serialized_start=76
  _RUNCROSTESTREQUEST._serialized_end=315
  _RUNCROSTESTREQUEST_AUTOTESTARG._serialized_start=273
  _RUNCROSTESTREQUEST_AUTOTESTARG._serialized_end=315
  _RUNCROSTESTRESPONSE._serialized_start=317
  _RUNCROSTESTRESPONSE._serialized_end=391
  _CROSTESTRUNNERSERVICE._serialized_start=393
  _CROSTESTRUNNERSERVICE._serialized_end=508
# @@protoc_insertion_point(module_scope)
