# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/test/api/cros_provision_metadata.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1chromiumos/test/api/cros_provision_metadata.proto\x12\x13\x63hromiumos.test.api\"\xc8\x01\n\x15\x43rOSProvisionMetadata\x12\x45\n\tdlc_specs\x18\x02 \x03(\x0b\x32\x32.chromiumos.test.api.CrOSProvisionMetadata.DLCSpec\x12\x19\n\x11preserve_stateful\x18\x03 \x01(\x08\x12\x17\n\x0fupdate_firmware\x18\x06 \x01(\x08\x12\x1d\n\x15only_googler_ssh_keys\x18\x04 \x01(\x08\x1a\x15\n\x07\x44LCSpec\x12\n\n\x02id\x18\x01 \x01(\tB/Z-go.chromium.org/chromiumos/config/go/test/apib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chromiumos.test.api.cros_provision_metadata_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z-go.chromium.org/chromiumos/config/go/test/api'
  _CROSPROVISIONMETADATA._serialized_start=75
  _CROSPROVISIONMETADATA._serialized_end=275
  _CROSPROVISIONMETADATA_DLCSPEC._serialized_start=254
  _CROSPROVISIONMETADATA_DLCSPEC._serialized_end=275
# @@protoc_insertion_point(module_scope)
