# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/test/api/post_test_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+chromiumos/test/api/post_test_service.proto\x12\x13\x63hromiumos.test.api\"\xb8\x01\n\x12RunActivityRequest\x12\x44\n\x13get_fw_info_request\x18\x01 \x01(\x0b\x32%.chromiumos.test.api.GetFWInfoRequestH\x00\x12Q\n\x1aget_files_from_dut_request\x18\x02 \x01(\x0b\x32+.chromiumos.test.api.GetFilesFromDUTRequestH\x00\x42\t\n\x07request\"\x12\n\x10GetFWInfoRequest\"\'\n\x16GetFilesFromDUTRequest\x12\r\n\x05\x66iles\x18\x01 \x03(\t\"\xbe\x01\n\x13RunActivityResponse\x12\x46\n\x14get_fw_info_response\x18\x01 \x01(\x0b\x32&.chromiumos.test.api.GetFWInfoResponseH\x00\x12S\n\x1bget_files_from_dut_response\x18\x02 \x01(\x0b\x32,.chromiumos.test.api.GetFilesFromDUTResponseH\x00\x42\n\n\x08response\"M\n\x11GetFWInfoResponse\x12\x0f\n\x07ro_fwid\x18\x01 \x01(\t\x12\x0f\n\x07rw_fwid\x18\x02 \x01(\t\x12\x16\n\x0ekernel_version\x18\x03 \x01(\t\"I\n\x17GetFilesFromDUTResponse\x12.\n\x08\x66ile_map\x18\x01 \x03(\x0b\x32\x1c.chromiumos.test.api.FileMap\"3\n\x07\x46ileMap\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x15\n\rfile_location\x18\x02 \x01(\t2s\n\x0fPostTestService\x12`\n\x0bRunActivity\x12\'.chromiumos.test.api.RunActivityRequest\x1a(.chromiumos.test.api.RunActivityResponseB/Z-go.chromium.org/chromiumos/config/go/test/apib\x06proto3')



_RUNACTIVITYREQUEST = DESCRIPTOR.message_types_by_name['RunActivityRequest']
_GETFWINFOREQUEST = DESCRIPTOR.message_types_by_name['GetFWInfoRequest']
_GETFILESFROMDUTREQUEST = DESCRIPTOR.message_types_by_name['GetFilesFromDUTRequest']
_RUNACTIVITYRESPONSE = DESCRIPTOR.message_types_by_name['RunActivityResponse']
_GETFWINFORESPONSE = DESCRIPTOR.message_types_by_name['GetFWInfoResponse']
_GETFILESFROMDUTRESPONSE = DESCRIPTOR.message_types_by_name['GetFilesFromDUTResponse']
_FILEMAP = DESCRIPTOR.message_types_by_name['FileMap']
RunActivityRequest = _reflection.GeneratedProtocolMessageType('RunActivityRequest', (_message.Message,), {
  'DESCRIPTOR' : _RUNACTIVITYREQUEST,
  '__module__' : 'chromiumos.test.api.post_test_service_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.api.RunActivityRequest)
  })
_sym_db.RegisterMessage(RunActivityRequest)

GetFWInfoRequest = _reflection.GeneratedProtocolMessageType('GetFWInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETFWINFOREQUEST,
  '__module__' : 'chromiumos.test.api.post_test_service_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.api.GetFWInfoRequest)
  })
_sym_db.RegisterMessage(GetFWInfoRequest)

GetFilesFromDUTRequest = _reflection.GeneratedProtocolMessageType('GetFilesFromDUTRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETFILESFROMDUTREQUEST,
  '__module__' : 'chromiumos.test.api.post_test_service_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.api.GetFilesFromDUTRequest)
  })
_sym_db.RegisterMessage(GetFilesFromDUTRequest)

RunActivityResponse = _reflection.GeneratedProtocolMessageType('RunActivityResponse', (_message.Message,), {
  'DESCRIPTOR' : _RUNACTIVITYRESPONSE,
  '__module__' : 'chromiumos.test.api.post_test_service_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.api.RunActivityResponse)
  })
_sym_db.RegisterMessage(RunActivityResponse)

GetFWInfoResponse = _reflection.GeneratedProtocolMessageType('GetFWInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETFWINFORESPONSE,
  '__module__' : 'chromiumos.test.api.post_test_service_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.api.GetFWInfoResponse)
  })
_sym_db.RegisterMessage(GetFWInfoResponse)

GetFilesFromDUTResponse = _reflection.GeneratedProtocolMessageType('GetFilesFromDUTResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETFILESFROMDUTRESPONSE,
  '__module__' : 'chromiumos.test.api.post_test_service_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.api.GetFilesFromDUTResponse)
  })
_sym_db.RegisterMessage(GetFilesFromDUTResponse)

FileMap = _reflection.GeneratedProtocolMessageType('FileMap', (_message.Message,), {
  'DESCRIPTOR' : _FILEMAP,
  '__module__' : 'chromiumos.test.api.post_test_service_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.api.FileMap)
  })
_sym_db.RegisterMessage(FileMap)

_POSTTESTSERVICE = DESCRIPTOR.services_by_name['PostTestService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z-go.chromium.org/chromiumos/config/go/test/api'
  _RUNACTIVITYREQUEST._serialized_start=69
  _RUNACTIVITYREQUEST._serialized_end=253
  _GETFWINFOREQUEST._serialized_start=255
  _GETFWINFOREQUEST._serialized_end=273
  _GETFILESFROMDUTREQUEST._serialized_start=275
  _GETFILESFROMDUTREQUEST._serialized_end=314
  _RUNACTIVITYRESPONSE._serialized_start=317
  _RUNACTIVITYRESPONSE._serialized_end=507
  _GETFWINFORESPONSE._serialized_start=509
  _GETFWINFORESPONSE._serialized_end=586
  _GETFILESFROMDUTRESPONSE._serialized_start=588
  _GETFILESFROMDUTRESPONSE._serialized_end=661
  _FILEMAP._serialized_start=663
  _FILEMAP._serialized_end=714
  _POSTTESTSERVICE._serialized_start=716
  _POSTTESTSERVICE._serialized_end=831
# @@protoc_insertion_point(module_scope)
