# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/config/api/test/harness/tauto/v1/tauto.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7chromiumos/config/api/test/harness/tauto/v1/tauto.proto\x12+chromiumos.config.api.test.harness.tauto.v1\"\x8f\x01\n\x0cTestMetadata\x12L\n\x04main\x18\x01 \x01(\x0b\x32>.chromiumos.config.api.test.harness.tauto.v1.TestMetadata.Main\x1a\x31\n\x04Main\x12\x16\n\x0epython_package\x18\x01 \x01(\t\x12\x11\n\ttest_args\x18\x02 \x03(\tBFZDgo.chromium.org/chromiumos/config/go/api/test/harness/tauto/v1;tautob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chromiumos.config.api.test.harness.tauto.v1.tauto_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZDgo.chromium.org/chromiumos/config/go/api/test/harness/tauto/v1;tauto'
  _TESTMETADATA._serialized_start=105
  _TESTMETADATA._serialized_end=248
  _TESTMETADATA_MAIN._serialized_start=199
  _TESTMETADATA_MAIN._serialized_end=248
# @@protoc_insertion_point(module_scope)
