# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/test/dut/device_stability.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromite.api.gen_sdk.chromiumos.test.api import dut_attribute_pb2 as chromiumos_dot_test_dot_api_dot_dut__attribute__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*chromiumos/test/dut/device_stability.proto\x12\x13\x63hromiumos.test.dut\x1a\'chromiumos/test/api/dut_attribute.proto\"\xcb\x01\n\x0f\x44\x65viceStability\x12\x37\n\x0c\x64ut_criteria\x18\x01 \x03(\x0b\x32!.chromiumos.test.api.DutCriterion\x12\x41\n\tstability\x18\x02 \x01(\x0e\x32..chromiumos.test.dut.DeviceStability.Stability\"<\n\tStability\x12\x15\n\x11STABILITY_UNKNOWN\x10\x00\x12\n\n\x06STABLE\x10\x01\x12\x0c\n\x08UNSTABLE\x10\x02\"K\n\x13\x44\x65viceStabilityList\x12\x34\n\x06values\x18\x01 \x03(\x0b\x32$.chromiumos.test.dut.DeviceStabilityB/Z-go.chromium.org/chromiumos/config/go/test/dutb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chromiumos.test.dut.device_stability_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z-go.chromium.org/chromiumos/config/go/test/dut'
  _DEVICESTABILITY._serialized_start=109
  _DEVICESTABILITY._serialized_end=312
  _DEVICESTABILITY_STABILITY._serialized_start=252
  _DEVICESTABILITY_STABILITY._serialized_end=312
  _DEVICESTABILITYLIST._serialized_start=314
  _DEVICESTABILITYLIST._serialized_end=389
# @@protoc_insertion_point(module_scope)
