# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/conductor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromite.api.gen_sdk.chromiumos import checkpoint_pb2 as chromiumos_dot_checkpoint__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63hromiumos/conductor.proto\x12\nchromiumos\x1a\x1b\x63hromiumos/checkpoint.proto\"\xe7\x01\n\tRetryRule\x12\x0e\n\x06status\x18\x01 \x03(\x05\x12\x17\n\x0f\x62uilder_name_re\x18\x02 \x03(\t\x12\x1b\n\x13summary_markdown_re\x18\x03 \x03(\t\x12\x30\n\x11\x66\x61iled_checkpoint\x18\x04 \x01(\x0e\x32\x15.chromiumos.RetryStep\x12\x16\n\x0e\x63utoff_percent\x18\x05 \x01(\x02\x12\x16\n\x0e\x63utoff_seconds\x18\x06 \x01(\x05\x12\x13\n\x0bmax_retries\x18\x07 \x01(\x05\x12\x1d\n\x15max_retries_per_build\x18\x08 \x01(\x05\"5\n\rCollectConfig\x12$\n\x05rules\x18\x01 \x03(\x0b\x32\x15.chromiumos.RetryRule\"\xcf\x01\n\x0f\x43onductorConfig\x12 \n\x18polling_interval_seconds\x18\x01 \x01(\x05\x12H\n\x0f\x63ollect_configs\x18\x02 \x03(\x0b\x32/.chromiumos.ConductorConfig.CollectConfigsEntry\x1aP\n\x13\x43ollectConfigsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.chromiumos.CollectConfig:\x02\x38\x01\x42Y\n!com.google.chrome.crosinfra.protoZ4go.chromium.org/chromiumos/infra/proto/go/chromiumosb\x06proto3')



_RETRYRULE = DESCRIPTOR.message_types_by_name['RetryRule']
_COLLECTCONFIG = DESCRIPTOR.message_types_by_name['CollectConfig']
_CONDUCTORCONFIG = DESCRIPTOR.message_types_by_name['ConductorConfig']
_CONDUCTORCONFIG_COLLECTCONFIGSENTRY = _CONDUCTORCONFIG.nested_types_by_name['CollectConfigsEntry']
RetryRule = _reflection.GeneratedProtocolMessageType('RetryRule', (_message.Message,), {
  'DESCRIPTOR' : _RETRYRULE,
  '__module__' : 'chromiumos.conductor_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.RetryRule)
  })
_sym_db.RegisterMessage(RetryRule)

CollectConfig = _reflection.GeneratedProtocolMessageType('CollectConfig', (_message.Message,), {
  'DESCRIPTOR' : _COLLECTCONFIG,
  '__module__' : 'chromiumos.conductor_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.CollectConfig)
  })
_sym_db.RegisterMessage(CollectConfig)

ConductorConfig = _reflection.GeneratedProtocolMessageType('ConductorConfig', (_message.Message,), {

  'CollectConfigsEntry' : _reflection.GeneratedProtocolMessageType('CollectConfigsEntry', (_message.Message,), {
    'DESCRIPTOR' : _CONDUCTORCONFIG_COLLECTCONFIGSENTRY,
    '__module__' : 'chromiumos.conductor_pb2'
    # @@protoc_insertion_point(class_scope:chromiumos.ConductorConfig.CollectConfigsEntry)
    })
  ,
  'DESCRIPTOR' : _CONDUCTORCONFIG,
  '__module__' : 'chromiumos.conductor_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.ConductorConfig)
  })
_sym_db.RegisterMessage(ConductorConfig)
_sym_db.RegisterMessage(ConductorConfig.CollectConfigsEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n!com.google.chrome.crosinfra.protoZ4go.chromium.org/chromiumos/infra/proto/go/chromiumos'
  _CONDUCTORCONFIG_COLLECTCONFIGSENTRY._options = None
  _CONDUCTORCONFIG_COLLECTCONFIGSENTRY._serialized_options = b'8\001'
  _RETRYRULE._serialized_start=72
  _RETRYRULE._serialized_end=303
  _COLLECTCONFIG._serialized_start=305
  _COLLECTCONFIG._serialized_end=358
  _CONDUCTORCONFIG._serialized_start=361
  _CONDUCTORCONFIG._serialized_end=568
  _CONDUCTORCONFIG_COLLECTCONFIGSENTRY._serialized_start=488
  _CONDUCTORCONFIG_COLLECTCONFIGSENTRY._serialized_end=568
# @@protoc_insertion_point(module_scope)
