# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/config/api/mfg_config_id.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)chromiumos/config/api/mfg_config_id.proto\x12\x15\x63hromiumos.config.api\"8\n\x0bMfgConfigId\x12\r\n\x05value\x18\x01 \x01(\t\x1a\x1a\n\nScanConfig\x12\x0c\n\x04hwid\x18\x01 \x01(\tB*Z(go.chromium.org/chromiumos/config/go/apib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chromiumos.config.api.mfg_config_id_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z(go.chromium.org/chromiumos/config/go/api'
  _MFGCONFIGID._serialized_start=68
  _MFGCONFIGID._serialized_end=124
  _MFGCONFIGID_SCANCONFIG._serialized_start=98
  _MFGCONFIGID_SCANCONFIG._serialized_end=124
# @@protoc_insertion_point(module_scope)
