# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/config/api/proximity_config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,chromiumos/config/api/proximity_config.proto\x12\x15\x63hromiumos.config.api\"\xc3\x07\n\x0fProximityConfig\x12\x41\n\x08location\x18\x01 \x03(\x0b\x32/.chromiumos.config.api.ProximityConfig.Location\x12U\n\rlegacy_config\x18\x02 \x01(\x0b\x32<.chromiumos.config.api.ProximityConfig.LegacyProximityConfigH\x00\x12W\n\x0esemtech_config\x18\x03 \x01(\x0b\x32=.chromiumos.config.api.ProximityConfig.SemtechProximityConfigH\x00\x12Y\n\x0f\x61\x63tivity_config\x18\x04 \x01(\x0b\x32>.chromiumos.config.api.ProximityConfig.ActivityProximityConfigH\x00\x1a\x9d\x01\n\x08Location\x12M\n\nradio_type\x18\x01 \x01(\x0e\x32\x39.chromiumos.config.api.ProximityConfig.Location.RadioType\x12\x10\n\x08modifier\x18\x02 \x01(\t\"0\n\tRadioType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04WIFI\x10\x01\x12\x0c\n\x08\x43\x45LLULAR\x10\x02\x1a\x17\n\x15LegacyProximityConfig\x1a\x83\x03\n\x16SemtechProximityConfig\x12\x63\n\x0e\x63hannel_config\x18\x01 \x03(\x0b\x32K.chromiumos.config.api.ProximityConfig.SemtechProximityConfig.ChannelConfig\x12\x1a\n\x12sampling_frequency\x18\x02 \x01(\x02\x12\x1d\n\x15thresh_falling_period\x18\x03 \x01(\r\x12\x1c\n\x14thresh_rising_period\x18\x04 \x01(\r\x1a\xaa\x01\n\rChannelConfig\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\x12\x14\n\x0chardwaregain\x18\x02 \x01(\r\x12\x16\n\x0ethresh_falling\x18\x03 \x01(\r\x12!\n\x19thresh_falling_hysteresis\x18\x04 \x01(\r\x12\x15\n\rthresh_rising\x18\x05 \x01(\r\x12 \n\x18thresh_rising_hysteresis\x18\x06 \x01(\r\x1a\x19\n\x17\x41\x63tivityProximityConfigB\x08\n\x06\x63onfigB*Z(go.chromium.org/chromiumos/config/go/apib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chromiumos.config.api.proximity_config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z(go.chromium.org/chromiumos/config/go/api'
  _PROXIMITYCONFIG._serialized_start=72
  _PROXIMITYCONFIG._serialized_end=1035
  _PROXIMITYCONFIG_LOCATION._serialized_start=426
  _PROXIMITYCONFIG_LOCATION._serialized_end=583
  _PROXIMITYCONFIG_LOCATION_RADIOTYPE._serialized_start=535
  _PROXIMITYCONFIG_LOCATION_RADIOTYPE._serialized_end=583
  _PROXIMITYCONFIG_LEGACYPROXIMITYCONFIG._serialized_start=585
  _PROXIMITYCONFIG_LEGACYPROXIMITYCONFIG._serialized_end=608
  _PROXIMITYCONFIG_SEMTECHPROXIMITYCONFIG._serialized_start=611
  _PROXIMITYCONFIG_SEMTECHPROXIMITYCONFIG._serialized_end=998
  _PROXIMITYCONFIG_SEMTECHPROXIMITYCONFIG_CHANNELCONFIG._serialized_start=828
  _PROXIMITYCONFIG_SEMTECHPROXIMITYCONFIG_CHANNELCONFIG._serialized_end=998
  _PROXIMITYCONFIG_ACTIVITYPROXIMITYCONFIG._serialized_start=1000
  _PROXIMITYCONFIG_ACTIVITYPROXIMITYCONFIG._serialized_end=1025
# @@protoc_insertion_point(module_scope)
