# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/config/api/software/rma_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/chromiumos/config/api/software/rma_config.proto\x12\x1e\x63hromiumos.config.api.software\"-\n\tRmaConfig\x12\x0f\n\x07\x65nabled\x18\x01 \x01(\x08\x12\x0f\n\x07has_cbi\x18\x02 \x01(\x08\x42\x33Z1go.chromium.org/chromiumos/config/go/api/softwareb\x06proto3')



_RMACONFIG = DESCRIPTOR.message_types_by_name['RmaConfig']
RmaConfig = _reflection.GeneratedProtocolMessageType('RmaConfig', (_message.Message,), {
  'DESCRIPTOR' : _RMACONFIG,
  '__module__' : 'chromiumos.config.api.software.rma_config_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.config.api.software.RmaConfig)
  })
_sym_db.RegisterMessage(RmaConfig)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z1go.chromium.org/chromiumos/config/go/api/software'
  _RMACONFIG._serialized_start=83
  _RMACONFIG._serialized_end=128
# @@protoc_insertion_point(module_scope)
