# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_platform/skylab_local_state/host_info.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0test_platform/skylab_local_state/host_info.proto\x12 test_platform.skylab_local_state\"\xdd\x01\n\x10\x41utotestHostInfo\x12V\n\nattributes\x18\x01 \x03(\x0b\x32\x42.test_platform.skylab_local_state.AutotestHostInfo.AttributesEntry\x12\x0e\n\x06labels\x18\x02 \x03(\t\x12.\n\x12serializer_version\x18\x03 \x01(\x05R\x12serializer_version\x1a\x31\n\x0f\x41ttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42LZJgo.chromium.org/chromiumos/infra/proto/go/test_platform/skylab_local_stateb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_platform.skylab_local_state.host_info_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZJgo.chromium.org/chromiumos/infra/proto/go/test_platform/skylab_local_state'
  _AUTOTESTHOSTINFO_ATTRIBUTESENTRY._options = None
  _AUTOTESTHOSTINFO_ATTRIBUTESENTRY._serialized_options = b'8\001'
  _AUTOTESTHOSTINFO._serialized_start=87
  _AUTOTESTHOSTINFO._serialized_end=308
  _AUTOTESTHOSTINFO_ATTRIBUTESENTRY._serialized_start=259
  _AUTOTESTHOSTINFO_ATTRIBUTESENTRY._serialized_end=308
# @@protoc_insertion_point(module_scope)
