# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_platform/skylab_local_state/receive.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.test_platform/skylab_local_state/receive.proto\x12 test_platform.skylab_local_state\"<\n\x0eReceiveRequest\x12\x13\n\x0bresults_dir\x18\x01 \x01(\t\x12\x15\n\rmessage_count\x18\x02 \x01(\x05\",\n\x0fReceiveResponse\x12\x19\n\x11received_messages\x18\x01 \x01(\x05\x42LZJgo.chromium.org/chromiumos/infra/proto/go/test_platform/skylab_local_stateb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_platform.skylab_local_state.receive_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZJgo.chromium.org/chromiumos/infra/proto/go/test_platform/skylab_local_state'
  _RECEIVEREQUEST._serialized_start=84
  _RECEIVEREQUEST._serialized_end=144
  _RECEIVERESPONSE._serialized_start=146
  _RECEIVERESPONSE._serialized_end=190
# @@protoc_insertion_point(module_scope)
